version: "3"

services:
  pricefeed:
    image: lcnem/botany-pricefeed
    extra_hosts:
      - host.docker.internal:172.101.0.1
    env_file:
      - .env
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/16
