version: '3'
services:
  botany:
    container_name: cosmoscan-with-extension
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4201:80