version: '3'
services:
  cosmoscan-jpyx:
    image: lcnem/cosmoscan-jpyx
    # build:
    #   context: ../../../../../
    #   dockerfile: ./botany/projects/cosmoscan-extension/editions/jpyx/Dockerfile
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
