#!/bin/bash

DOMEIN_CAUCHYE=a.private-test.ununifi.cauchye.net
RUNNING_FRONT=TRUE
RUNNING_FAUCET=TRUE
SETUP_SSL_NODE_CONFIG_ENV=TRUE

export DOMEIN_CAUCHYE=$DOMEIN_CAUCHYE
export RUNNING_FRONT=$RUNNING_FRONT
export RUNNING_FAUCET=$RUNNING_FAUCET
export SETUP_SSL_NODE_CONFIG_ENV=$SETUP_SSL_NODE_CONFIG_ENV
