name: telescope Action Trigger Publish Docker image for Private Testnet telescope-ununifi
on:
  repository_dispatch:
    types:
      - repository-telescope-new-release-for-private-testnet
jobs:
  push_to_registry:
    name: Push Docker image for Private Testnet to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/telescope-extension/editions/ununifi/Dockerfile-private-test
          push: true
          tags: |
            ghcr.io/ununifi/telescope-ununifi:test
