name: telescope Action Trigger Publish Docker image telescope-ununifi
on:
  repository_dispatch:
    types:
      - repository-telescope-new-release
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/telescope-extension/editions/jpyx/Dockerfile
          push: true
          tags: |
            ghcr.io/UnUniFi/telescope-ununifi:latest
