name: Build Docker image telescope-jpyx

on:
  pull_request:
    paths:
      - "projects/telescope-extension/**"
      - "projects/shared/**"
      - "common/**"
      - "package-lock.json"
      - "package.json"

jobs:
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Build only
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/telescope-extension/editions/jpyx/Dockerfile
          push: false
          tags: |
            ghcr.io/UnUniFi/telescope-ununifi:test
