name: Node.js CI telescope-ununifi

on:
  pull_request:
    paths:
      - "projects/telescope-extension/**"
      - "projects/shared/**"
      - "common/**"
      - "package-lock.json"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i -g npm
      - run: npm ci
      - run: npm run build --if-present -- --project=telescope-extension
      - run: npm run test -- --watch=false --browsers=ChromeHeadless --project=telescope-extension
        env:
          CI: true
